import os

def create_ai_wrapper(project_path):
    wrapper_path = os.path.join(project_path, "automend_runner.py")

    code = """
# AUTO-GENERATED BY AUTOMEND AI
# Purpose: Safely demonstrate library execution

import inspect
import sys

def main():
    print("AUTOMEND AI – Library Execution Demo")

    for name, obj in globals().items():
        if callable(obj) and not name.startswith("_"):
            try:
                print(f"{name}(2, 3) =", obj(2, 3))
            except Exception:
                pass

if __name__ == "__main__":
    main()
"""

    with open(wrapper_path, "w", encoding="utf-8") as f:
        f.write(code)

    return wrapper_path
