import subprocess
import tempfile
import os


def is_valid_diff(patch_text: str) -> bool:
    """
    Check whether patch looks like a valid unified diff
    """
    if not patch_text:
        return False

    required_markers = ["--- ", "+++ ", "@@"]
    return all(marker in patch_text for marker in required_markers)


def apply_patch(project_path: str, patch_text: str) -> dict:
    """
    Safely applies a git patch.
    Never crashes the server.
    """

    # 1️⃣ Empty patch → skip safely
    if not patch_text or not patch_text.strip():
        return {
            "applied": False,
            "reason": "Empty patch generated by AI"
        }

    # 2️⃣ Invalid diff format → skip safely
    if not is_valid_diff(patch_text):
        return {
            "applied": False,
            "reason": "Invalid diff format"
        }

    # 3️⃣ Write patch to temp file
    with tempfile.NamedTemporaryFile(
        delete=False,
        mode="w",
        suffix=".diff",
        encoding="utf-8"
    ) as patch_file:
        patch_file.write(patch_text)
        patch_path = patch_file.name

    try:
        # 4️⃣ Apply patch
        result = subprocess.run(
            ["git", "apply", patch_path],
            cwd=project_path,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )

        if result.returncode != 0:
            return {
                "applied": False,
                "reason": result.stderr.strip()
            }

        return {
            "applied": True,
            "reason": "Patch applied successfully"
        }

    finally:
        if os.path.exists(patch_path):
            os.remove(patch_path)
